version: '3.2'

services:

  harvester:
    build: harvester/.
    image: polkascan/harvester
    restart: unless-stopped
    entrypoint: /usr/src/start.sh
    ports:
      - '9620:9616'
    environment:
      - DB_CONNECTION=mysql+pymysql://admin:admin12345@shearscan-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com:3306/shearscan_db?charset=utf8mb4
      - SUBSTRATE_RPC_URL=wss://www.sheartoken.com
#      - SUBSTRATE_RPC_URL=ws://host.docker.internal:9944
      - NODE_TYPE=archive
      - SUBSTRATE_SS58_FORMAT=42
      - INSTALLED_ETL_DATABASES=shearscan_explorer
    depends_on:
      - mysql
      # - substrate-node

  polling:
    build:
      context: explorer-api/.
      dockerfile: ./docker/polling/Dockerfile
    image: polkascan/explorer-polling
    restart: unless-stopped
    command: python polling.py
    depends_on:
      - redis
      - mysql
    environment:
      - DB_USERNAME=admin
      - DB_NAME=shearscan_explorer
      - DB_HOST=shearscan-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_PASSWORD=admin12345
      - BROADCAST_URI=redis://redis:6379
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-polling-v2
      - SENTRY_SERVER_NAME=shearscan
      - SENTRY_DSN=
      - BLOCK_LIMIT_COUNT=500000

  api:
    build:
      context: explorer-api/.
      dockerfile: ./docker/api/Dockerfile
    image: polkascan/explorer-api
    restart: unless-stopped
    command: bash -c "/usr/src/start-api.sh"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    environment:
      - DB_USERNAME=admin
      - DB_NAME=shearscan_explorer
      - DB_HOST=shearscan-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_PASSWORD=admin12345
      - DB_HARVESTER_NAME=shearscan_db
      - DOMAIN=localhost
      - SERVER_ADDR=localhost
      - SERVER_PORT=8000
      - WEBSOCKET_URI=wss://wss.sheartoken.com
      - BACKEND_CORS_ORIGINS=[]
      - BROADCAST_URI=redis://redis:6379
      - API_SQLA_URI=mysql+pymysql://admin:admin12345@shearscan-db.czs1e81qdbcu.eu-central-1.rds.amazonaws.com:3306/shearscan_explorer?charset=utf8mb4
      - CHAIN_ID=polkadot
      - SENTRY_PROJECT_NAME=explorer-api-v2
      - SENTRY_SERVER_NAME=polkadapt
      - SENTRY_DSN=
      - BLOCK_LIMIT_COUNT=500000

  gui:
    build:
      context: explorer-ui/.
    image: polkascan/explorer-ui
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api


  redis:
    image: "redis:latest"

volumes:
  mysql-data:

